This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./rapport_de_stage_gousselot_theophile.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file rapport_de_stage_gousselot_theophile.acn...done (0 entries accepted, 0 rejected).
Nothing written in rapport_de_stage_gousselot_theophile.acr.
Transcript written in rapport_de_stage_gousselot_theophile.alg.
